// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/Action/index.vue')['default']
    Cell: typeof import('./src/components/Cell/index.vue')['default']
    CellGroup: typeof import('./src/components/CellGroup/index.vue')['default']
    Divider: typeof import('./src/components/Divider/index.vue')['default']
    Elevator: typeof import('./src/components/Elevator/index.vue')['default']
    Engine: typeof import('./src/components/Engine/index.vue')['default']
    FixedNav: typeof import('./src/components/FixedNav/index.vue')['default']
    Grid: typeof import('./src/components/Grid/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Indicator: typeof import('./src/components/Indicator/index.vue')['default']
    Navbar: typeof import('./src/components/Navbar/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutElevator: typeof import('@nutui/nutui-taro')['Elevator']
    NutFixedNav: typeof import('@nutui/nutui-taro')['FixedNav']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIndicator: typeof import('@nutui/nutui-taro')['Indicator']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    Page: typeof import('./src/components/Page/index.vue')['default']
    ProForm: typeof import('./src/components/ProForm/index.vue')['default']
    ProFormField: typeof import('./src/components/ProFormField/index.vue')['default']
    Render: typeof import('./src/components/Render/index.vue')['default']
    Row: typeof import('./src/components/Row/index.vue')['default']
    Sticky: typeof import('./src/components/Sticky/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/index.vue')['default']
  }
}
