// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Cell: typeof import('./src/components/cell/cell.vue')['default']
    Cellgroup: typeof import('./src/components/cellgroup/cellgroup.vue')['default']
    Divider: typeof import('./src/components/divider/divider.vue')['default']
    Elevator: typeof import('./src/components/elevator/elevator.vue')['default']
    Engine: typeof import('./src/components/engine/engine.vue')['default']
    Fixednav: typeof import('./src/components/fixednav/fixednav.vue')['default']
    Grid: typeof import('./src/components/grid/grid.vue')['default']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
    Indicator: typeof import('./src/components/indicator/indicator.vue')['default']
    Navbar: typeof import('./src/components/navbar/navbar.vue')['default']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutElevator: typeof import('@nutui/nutui-taro')['Elevator']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIndicator: typeof import('@nutui/nutui-taro')['Indicator']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutSticky: typeof import('@nutui/nutui-taro')['Sticky']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    Page: typeof import('./src/components/page/page.vue')['default']
    Render: typeof import('./src/components/render/render.vue')['default']
    Row: typeof import('./src/components/row/row.vue')['default']
    Sticky: typeof import('./src/components/sticky/sticky.vue')['default']
  }
}
